version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
    #  - ./data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # инициализация БД из SQL-дампа
    environment:
      POSTGRES_DB: tipOnlineShop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    #image: go-app:latest
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: tipOnlineShop
      DB_PORT: "5432"     # Важно: строкой, чтобы избежать парсинга как число
    ports:
      - "8080:8080"
