name: Go App CI/CD

on:
  push:
    branches: [ main ]  # запускается при пуше в main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.20

      - name: Install dependencies
        run: go mod download

      - name: Run tests (skip if none)
        run: go test ./... || echo "No tests found"

      - name: Build Docker image
        run: docker build -t my-go-app .

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "docker-compose.yml"
          target: "~/go-app"

      - name: SSH and restart docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ~/go-app
            docker-compose down
            docker-compose up -d --build
