name: Go App CI/CD

on:
  push:
    branches: [ main ]  # запускается при пуше в main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repo
        uses: actions/checkout@v3

      # Шаг 2: Сборка Docker-образа на GitHub Actions
      - name: Build Docker image
        run: docker build -t my-go-app .

      # Шаг 3: Экспорт Docker-образа в файл
      - name: Save Docker image as tar
        run: docker save my-go-app | gzip > my-go-app.tar.gz

      # Шаг 4: Передача tar-архива с образом на сервер через SCP
      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "my-go-app.tar.gz"
          target: "~/go-app/"

      # Шаг 5: SSH и загрузка образа на сервер
      - name: SSH and load Docker image on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd ~/go-app
            # Распаковываем и загружаем Docker-образ
            gunzip -c my-go-app.tar.gz | docker load
            # Запуск контейнера
            docker-compose down
            docker-compose up -d
